### ISSUE TITLE
Renaming .h5 file erases data?

### ISSUE THREAD

**Issue by ArvidJB** [Quansight/versioned-hdf5#28]
This is a pretty strange bug: after renaming the file and opening it with the new name:
```
import os

import h5py
import numpy as np

from versioned_hdf5 import VersionedHDF5File

with h5py.File('foo1.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        sv['a'] = np.array([1, 2, 3])

os.rename('foo1.h5', 'foo2.h5')

with h5py.File('foo2.h5', 'r') as f:
    vf = VersionedHDF5File(f)
    v0 = vf['0']
    print(v0['a'][:])
```
it prints `[0 0 0]` instead of the expected `[1 2 3]`!

What's strange is that the file contents seem to change during the rename! I ran an h5dump before and after the rename:
```
> h5dump foo1.h5 > foo1.h5.dump
> h5dump foo2.h5 > foo2.h5.dump
> diff foo1.h5.dump foo2.h5.dump
1c1
< HDF5 "foo1.h5" {
---
> HDF5 "foo2.h5" {
16665c16665
<                (0): 1, 2, 3
---
>                (0): 0, 0, 0
```
This seems to happen with h5py version 2.9 and 2.10.

**Comment by asmeurer** [comment]
This is related to #23. However, I think there is more going on because even in that branch I get the same issue.

**Comment by asmeurer** [comment]
Just taking shasums, the file itself doesn't change from the rename or the File('r'). 

It seems like somehow the filename is being encoded into the file, so that reads only work if the filename is the same. If you rename the file back to foo1.h5, it works again. 

I'm not sure how this is happening.

**Comment by asmeurer** [comment]
Oh it's because of the way virtual datasets work, they can point to arbitrary files. So if the filename changes, it won't be able to find the data it points to (it's unfortunate that hdf5 just gives 0s when this happens instead of an error). I will look into whether it can be made filename agnostic when pointing to the same file.

**Comment by asmeurer** [comment]
I didn't see anything yet, but I will keep looking. Virtual datasets are unfortunately an underdocumented feature of HDF5. If it is not possible we will need to document it and provide a helper function to rename the files. 

I will also investigate whether HDF5 really reads 0s without an error or if this is just h5py ignoring the error.

**Comment by ArvidJB** [comment]
Wow, that's an interesting "feature"....
For now, as a workaround, I will just skip renaming the file. We do that to make the .h5 file creation atomic by first writing to a unique temp file before renaming it to the proper name.

**Comment by asmeurer** [comment]
Looking into this some more.

It seems that HDF5 does indicate error on read, but from what I can tell, h5py ignores it. See https://support.hdfgroup.org/HDF5/doc/RM/RM_H5D.html#Dataset-Read

> Returns:
>    Returns a non-negative value if successful; otherwise returns a negative value. 

and https://github.com/h5py/h5py/blob/79fbe27727dfda04174dba28a9e65b749ecadf84/h5py/_proxy.pyx#L140

I don't know if this is intentional behavior on the part of hdf5.

But the good news is after perusing the HDF5 source code, I found this

https://github.com/HDFGroup/hdf5/blob/88a39adaa2e2a35ef385896cac6c209abc4f388f/src/H5Dvirtual.c#L928

We can set the file path to `"."` to use the same file. This isn't documented anywhere in the HDF5 docs that I saw.

I tested it, and it seems to work.

**Comment by asmeurer** [comment]
@scopatz just to clarify here, the non-error reporting is from h5py:

```py
>>> import h5py
>>> f = h5py.File('test.hdf5', 'w')
>>> f.create_dataset('base', data=[1, 2, 3])
<HDF5 dataset "base": shape (3,), type "<i8">
>>> layout = h5py.VirtualLayout(f['base'].shape)
>>> vs = h5py.VirtualSource(f['base'])
>>> layout[:] = vs[:]
>>> f.create_virtual_dataset('virtual', layout)
<HDF5 dataset "virtual": shape (3,), type "<f4">
>>> f['virtual'][:]
array([1., 2., 3.], dtype=float32)
```

```
$ mv test.hdf5 test2.hdf5
```

```py
>>> import h5py
>>> f = h5py.File('test2.hdf5', 'r')
>>> f['virtual'][:]
array([0., 0., 0.], dtype=float32)
```

**Comment by asmeurer** [comment]
It seems that h5py does translate hdf5 errors into exceptions (it happens at a lower level than where I was looking). However, it seems like H5DRead doesn't give an error for the bad filename. I can't tell if it is supposed to not.

**Comment by asmeurer** [comment]
I opened an upstream issue in the lack of an error from h5py https://github.com/h5py/h5py/issues/1546.

**Comment by asmeurer** [comment]
@ArvidJB @quarl will you need support for fill values (missing data)? I haven't implemented them yet. If we don't need to support them, we can set the fill value on the virtual dataset to nan instead of the default 0, so that it gives a better indication that something has gone wrong when something like this happens.

**Comment by quarl** [comment]
We do rely on create_dataset(fillvalue=...).
We have a (from your perspective) application-specific choice of fill value.
Also, we have integer/string/etc data sets, where we can't use NaN.
